Repository BHoM/RAM_Toolkit, pull requests merged in 2020-06, with the labels that each got.

#144 Update referencing and post build
  RAM_Adapter/RAM_Adapter.csproj
  RAM_Engine/RAM_Engine.csproj
  RAM_oM/RAM_oM.csproj
Labels: type:external-api-changes

#145 Aligning with changes migrating Results to Analytical_oM
  RAM_Adapter/AdapterActions/_Pullmethods/ReadResults.cs
  RAM_Adapter/CRUD/Read.cs
  RAM_Adapter/CRUD/UpdateObjects.cs
  RAM_Adapter/RAM_Adapter.csproj
  RAM_Adapter/Types/Comparer.cs
  RAM_Adapter/Types/DependencyTypes.cs
  RAM_Engine/RAM_Engine.csproj
Labels: type:external-api-changes

#146 Align with changes in Structure_oM making results immutable
  RAM_Adapter/Convert/ToBHoM.cs
Labels: type:external-api-changes

#149 Updated readme
  README.md
Labels: type:documentation

#152 Stories tweaked and check added for overlapping wall openings
  RAM_Adapter/CRUD/Create.cs
  RAM_Adapter/Convert/ToBHoM.cs
Labels: type:bug
